Updated external files

diff --git a/tools/maint/fetch.in b/tools/maint/fetch.in
--- a/tools/maint/fetch.in
+++ b/tools/maint/fetch.in
@@ -24,6 +24,7 @@ me="fetch"
 version="0.1"
 
 WGET=@WGET@
+WGET_FLAGS="--timestamping --no-verbose -q -O"
 
 case $1 in
     -h|--help)
@@ -56,6 +57,11 @@ if test "$WGET" = "" ; then
     echo "$me: Missing wget executable ..."
     exit 1
 fi
+if test "$WGET" = "@""WGET""@" ; then
+    echo "$me: Missing wget autoconf substitution ..."
+    exit 1
+fi
+
 if test "$URL" = "" ; then
     echo "$me: Missing input URL"
     echo "Try \`$program --help' for more information."
@@ -67,9 +73,9 @@ if test "$FILE" = "" ; then
     exit 1
 fi
 
-echo "$me: $URL"
+echo "$me: $URL -> $FILE"
 rm -f $FILE
-$WGET --no-verbose -q -O $FILE -- $URL || {
+$WGET $WGET_FLAGS $FILE -- $URL || {
     echo "$me: Cannot fetch $URL"
     rm -f $FILE
     exit 1
@@ -80,5 +86,7 @@ if test ! -s $FILE ; then
     rm -f $FILE
     exit 1
 fi
+
+touch $FILE
 
 exit 0
