Added missing rule

diff --git a/tools/maint/Makefile.am b/tools/maint/Makefile.am
--- a/tools/maint/Makefile.am
+++ b/tools/maint/Makefile.am
@@ -57,4 +57,15 @@ update-local: Makefile
 	done && \
 	rm -r -f fetch-dir
 
+maintainer-check-parameters: Makefile $(scripts)
+	for i in $(scripts) ; do \
+		echo @ECHO_N@ "Checking standard parameters for $$i... " ; \
+		if ( ./$$i -h 2>&1 > /dev/null ) ; then \
+			echo "@ECHO_T@ok" ; \
+		else \
+			echo "@ECHO_T@error" ; \
+			exit 1 ; \
+		fi ; \
+	done
+
 maintainer-check-local: Makefile maintainer-check-parameters
