Fixed maintainer-check rule

diff --git a/src/Makefile.am b/src/Makefile.am
--- a/src/Makefile.am
+++ b/src/Makefile.am
@@ -98,5 +98,16 @@ all_SRCS =					\
 	$(bfd_section_ls_SOURCES)		\
 	$(bfd_section_mv_SOURCES)
 
-maintainer-check-local: Makefile
+maintainer-check-parameters: Makefile $(bin_PROGRAMS)
+	for i in $(bin_PROGRAMS) ; do \
+		echo @ECHO_N@ "Checking standard parameters for $$i... " ; \
+		if ( ./$$i -h 2>&1 > /dev/null ) ; then \
+			echo "@ECHO_T@ok" ; \
+		else \
+			echo "@ECHO_T@error" ; \
+			exit 1 ; \
+		fi ; \
+	done
+
+maintainer-check-local: Makefile maintainer-check-parameters
 	$(WHITESPACE_DETECT)  $(all_SRCS)
